import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { recruitmentTypes, sourceFacts } from "@/lib/recruitment";
import snapshot from "@/data/career-snapshot.json";
import { curatedJobs } from "@/lib/curated-jobs";
import { extractEligibility } from "@/lib/eligibility";
import { employersForSearch, type BoardProvider, type EmployerSource } from "@/lib/employers";
import { locationTerms } from "@/lib/locations";
import { deduplicateJobs, extractSalary, getFreshness, inferExperience, isSeniorRole, tokens } from "@/lib/matching";
import { occupationPhrases } from "@/lib/occupations";
import { filterWithDiagnostics, matchesRequestedLocation } from "@/lib/search-quality";
import { employerRegistry } from "@/lib/employers";
import { cached, circuitOpen, FEED_TTL_MS, mapConcurrent, recordFailure, recordSuccess, SEARCH_TTL_MS } from "@/lib/server-cache";
import type { GeographyScope, Job, JobSource, Qualification, RoleCategory, SearchResponse, SourceHealth, WorkplaceMode } from "@/lib/types";

export const runtime = "nodejs";
export const revalidate = 300;
export const maxDuration = 180;

const roleCategories = ["custom", "software", "electrical", "automation", "get", "sales", "marketing", "management", "finance", "hr", "design", "data", "operations", "support", "healthcare", "education", "science", "legal", "hospitality", "retail", "construction", "trades", "administration", "media", "agriculture", "social", "remote"] as const;
const searchSchema = z.object({
  recruitment: z.enum(["any", "off-campus", "campus", "fresher", "graduate", "internship", "apprenticeship"]).default("any"),
  q: z.string().trim().max(100).default(""), category: z.enum(roleCategories).default("custom"), categories: z.string().max(500).default(""),
  roles: z.string().max(1000).default(""), mode: z.enum(["exact", "balanced", "broad"]).default("balanced"), required: z.string().trim().max(300).default(""), optional: z.string().trim().max(300).default(""),
  industry: z.enum(["any", "technology", "manufacturing", "healthcare", "education", "finance", "retail", "construction", "hospitality", "energy", "public", "nonprofit"]).default("any"),
  location: z.string().trim().max(160).default(""), scope: z.enum(["india", "international", "any"]).default("any"),
  workplace: z.enum(["any", "remote", "hybrid", "onsite"]).default("any"), workplaces: z.string().max(100).default(""), remote: z.enum(["true", "false"]).optional(),
  experience: z.enum(["fresher", "entry", "experienced", "any"]).default("any"), qualification: z.enum(["any", "school", "iti", "diploma", "undergraduate", "btech", "postgraduate", "phd", "professional"]).default("any"),
  schedule: z.enum(["any", "full-time", "part-time", "contract", "internship", "temporary", "volunteer"]).default("any"), relocation: z.enum(["any", "yes", "no"]).default("any"), nearby: z.enum(["true", "false"]).default("true"),
  negative: z.string().trim().max(300).default(""), boards: z.string().max(4000).default("")
});

const RATE_LIMIT = 40;
const WINDOW_MS = 60_000;
const rateBuckets = new Map<string, { count: number; resetAt: number }>();
const aliases: Record<RoleCategory, string[]> = {
  custom: [], software: ["software engineer", "software developer", "frontend", "backend", "full stack", "sde", "mobile engineer", "devops"],
  electrical: ["electrical engineer", "electrical design", "power systems", "maintenance engineer", "electronics engineer"], automation: ["automation engineer", "control engineer", "plc", "scada", "instrumentation", "mechatronics"],
  get: ["graduate engineer trainee", "graduate trainee", "engineer trainee", "apprentice", "fresher", "new graduate"], sales: ["sales", "account executive", "business development", "partnerships", "customer success"],
  marketing: ["marketing", "growth", "brand", "content", "seo", "communications"], management: ["manager", "program manager", "project manager", "product manager", "strategy"],
  finance: ["finance", "financial analyst", "accounting", "audit", "tax"], hr: ["human resources", "people operations", "recruiter", "talent acquisition"], design: ["designer", "product design", "ux", "ui", "creative"],
  data: ["data analyst", "data scientist", "data engineer", "analytics", "machine learning"], operations: ["operations", "supply chain", "procurement", "logistics"], support: ["customer support", "technical support", "customer service"],
  healthcare: ["healthcare", "clinical", "nurse", "medical", "pharmacist", "therapist"], education: ["teacher", "faculty", "lecturer", "education", "academic", "counsellor"], science: ["scientist", "research", "laboratory", "chemist", "biologist"],
  legal: ["legal", "lawyer", "counsel", "paralegal", "compliance"], hospitality: ["hospitality", "hotel", "chef", "restaurant", "front office", "guest service", "reservation", "housekeeping", "food and beverage"], retail: ["retail", "store", "merchandising", "cashier"],
  construction: ["construction", "civil engineer", "site engineer", "architect", "quantity surveyor"], trades: ["electrician", "technician", "welder", "fitter", "machinist", "operator"],
  administration: ["administration", "administrative assistant", "office assistant", "admin executive", "back office", "executive assistant", "office coordinator", "secretary", "clerical", "receptionist"], media: ["journalist", "editor", "writer", "media", "communications", "public relations", "video"],
  agriculture: ["agriculture", "agronomy", "food science", "forestry", "environment", "sustainability"], social: ["social work", "community", "nonprofit", "ngo", "public policy", "development sector"], remote: ["software", "product", "sales", "marketing", "operations", "support"]
};
const categoryTitlePatterns: Partial<Record<RoleCategory, RegExp>> = {
  software: /\b(software|developer|frontend|backend|full[ -]?stack|sde|cloud|devops|mobile|web|platform|quality|test)\b/i, electrical: /\b(electrical|electronics|power|maintenance|substation|energy|embedded|hardware)\b/i,
  automation: /\b(automation|control|plc|scada|instrumentation?|robot(?:ics)?|mechatronics?)\b/i, get: /\b(graduate|trainee|apprentice|fresher|new grad|intern(?:ship)?)\b/i,
  sales: /\b(sales|account executive|business development|partnerships|revenue|customer success)\b/i, marketing: /\b(marketing|growth|brand|content|seo|communications?|demand generation)\b/i,
  management: /\b(manager|management|director|strategy|product lead|program lead|project lead)\b/i, finance: /\b(finance|financial|accounting|accountant|audit|tax|treasury|controller)\b/i,
  hr: /\b(human resources|people|recruiter|recruiting|talent|hrbp)\b/i, design: /\b(design|designer|ux|ui|creative|researcher)\b/i, data: /\b(data|analytics?|business intelligence|machine learning|ml engineer|ai engineer)\b/i,
  operations: /\b(operations?|supply chain|procurement|logistics|coordinator|program)\b/i, support: /\b(support|customer service|customer success|helpdesk|service desk)\b/i,
  healthcare: /\b(healthcare|clinical|nurse|medical|medicine|pharmacist|therapy|physician|doctor|dentist|patient care)\b/i, education: /\b(teacher|teaching|faculty|lecturer|professor|academic|education|school|curriculum)\b/i,
  science: /\b(scientist|research|laboratory|chemist|biology|physics|materials)\b/i, legal: /\b(legal|lawyer|counsel|paralegal|compliance)\b/i, hospitality: /\b(hospitality|hotel|chef|restaurant|front office|food and beverage|guest service|reservation|housekeeping)\b/i,
  retail: /\b(retail|store|merchandis|cashier|shop)\b/i, construction: /\b(construction|civil|site engineer|architect|quantity surveyor|building)\b/i, trades: /\b(electrician|technician|welder|fitter|machinist|operator|mechanic)\b/i,
  administration: /\b(administrat\w*|admin executive|back office|office (?:assistant|coordinator|manager)|secretar\w*|clerical|reception\w*|executive assistant)\b/i, media: /\b(journalis|editor|writer|media|communications?|public relations|video|producer|broadcast)\b/i,
  agriculture: /\b(agricultur|agronom|food science|forestry|environment|sustainab|horticultur|veterinar)\b/i, social: /\b(social work|community|nonprofit|ngo|public policy|development sector|humanitarian|programme officer)\b/i
};
const qualificationTerms: Record<Qualification, string[]> = {
  any: [], school: ["high school", "secondary school", "10th", "12th"], iti: ["iti", "industrial training institute"], diploma: ["diploma"], undergraduate: ["undergraduate", "bachelor", "degree", "graduate"],
  btech: ["b.tech", "btech", "b.e", "bachelor of engineering"], postgraduate: ["postgraduate", "master", "mba", "m.tech", "m.sc"], phd: ["ph.d", "phd", "doctorate"], professional: ["ca", "cfa", "cpa", "pmp", "professional certification"]
};
const industryTerms: Record<string, string[]> = {
  any: [], technology: ["software", "technology", "cloud", "data", "digital"], manufacturing: ["manufacturing", "factory", "plant", "production", "industrial"], healthcare: ["healthcare", "hospital", "clinical", "medical", "pharma"], education: ["education", "school", "university", "learning", "academic"], finance: ["finance", "bank", "insurance", "fintech", "accounting"], retail: ["retail", "store", "ecommerce", "consumer"], construction: ["construction", "infrastructure", "building", "civil"], hospitality: ["hospitality", "hotel", "restaurant", "travel"], energy: ["energy", "power", "oil", "gas", "renewable", "utilities"], public: ["government", "public sector", "civil service"], nonprofit: ["nonprofit", "ngo", "community", "humanitarian"]
};
const indianPlaces = /\b(india|bengaluru|bangalore|delhi|gurugram|gurgaon|noida|lucknow|pune|mumbai|hyderabad|chennai|kolkata|ahmedabad|vadodara|jaipur|patna|bihar|uttar pradesh|haryana|karnataka|maharashtra|telangana|tamil nadu|kerala|andhra pradesh|ncr|remote india)\b/i;
const worldwidePlaces = /\b(worldwide|anywhere|global|all countries|multiple locations)\b/i;
const cityAliases: Record<string, string[]> = { delhi: ["delhi", "new delhi", "delhi ncr", "ncr", "gurugram", "gurgaon", "noida"], "new delhi": ["delhi", "new delhi", "ncr", "gurugram", "noida"], gurugram: ["gurugram", "gurgaon", "delhi ncr", "ncr"], gurgaon: ["gurugram", "gurgaon", "ncr"], bangalore: ["bangalore", "bengaluru"], bengaluru: ["bangalore", "bengaluru"], usa: ["usa", "united states", "u.s."], "united states": ["usa", "united states", "u.s."], uk: ["uk", "united kingdom", "england"] };

type BoardTarget = Pick<EmployerSource, "provider" | "slug" | "name">;
type SourceTask = { name: string; source: JobSource; key: string; ttl?: number; load: () => Promise<Job[]> };
const clean = (html: string) => html.replace(/<[^>]*>/g, " ").replace(/&nbsp;|&amp;|&lt;|&gt;|&#39;|&quot;/g, " ").replace(/\s+/g, " ").trim().slice(0, 4000);
const stringArray = (value: unknown) => Array.isArray(value) ? value.map((item) => typeof item === "object" && item ? String((item as Record<string, unknown>).label ?? (item as Record<string, unknown>).name ?? "") : String(item)).filter(Boolean).slice(0, 12) : [];
const safeUrl = (value: string) => { try { const url = new URL(value); return ["https:", "http:"].includes(url.protocol) ? url.toString() : ""; } catch { return ""; } };
function inferWorkplace(context: string, remote = false): Job["workplace"] { if (/\bhybrid\b/i.test(context)) return "hybrid"; if (remote || /\b(remote|work from home|distributed)\b/i.test(context)) return "remote"; if (/\b(on[ -]?site|in[ -]?office|office based)\b/i.test(context)) return "onsite"; return "unknown"; }
function finish(job: Omit<Job, "experienceLevel" | "freshness" | "salaryText" | "workplace"> & { workplace?: Job["workplace"] }): Job {
  const context = `${job.title} ${job.location} ${job.description} ${job.tags.join(" ")}`; const workplace = job.workplace ?? inferWorkplace(context, job.remote);
  const base: Job = { ...job, recruitmentTypes: recruitmentTypes(job), remote: workplace === "remote", workplace, url: safeUrl(job.url), experienceLevel: inferExperience(context), freshness: getFreshness(job.publishedAt), salaryText: extractSalary(context) };
  return { liveStatus: "live", liveStatusReason: "Present in the source's current public feed.", ...base, ...extractEligibility(base) };
}
async function fetchJson(url: string, timeout = 7000): Promise<unknown> {
  let lastError: unknown;
  for (let attempt = 0; attempt < 2; attempt += 1) try {
    const response = await fetch(url, { signal: AbortSignal.timeout(timeout), cache: "no-store", headers: { Accept: "application/json", "User-Agent": "VEYRA/2.0 public-job-discovery" } });
    if (!response.ok) throw new Error(`Source returned ${response.status}`); return response.json();
  } catch (error) { lastError = error; }
  throw lastError;
}
async function remotive(): Promise<Job[]> { const data = await fetchJson("https://remotive.com/api/remote-jobs?limit=100") as { jobs?: Array<Record<string, unknown>> }; return (data.jobs ?? []).map((item) => finish({ id: `remotive-${String(item.id)}`, title: String(item.title ?? "Untitled role"), company: String(item.company_name ?? "Unknown company"), location: String(item.candidate_required_location ?? "Remote"), remote: true, workplace: "remote", source: "Remotive", url: String(item.url ?? ""), publishedAt: String(item.publication_date ?? ""), description: clean(String(item.description ?? "")), tags: stringArray(item.tags), employmentType: String(item.job_type ?? "") })); }
async function arbeitnow(): Promise<Job[]> { const data = await fetchJson("https://www.arbeitnow.com/api/job-board-api") as { data?: Array<Record<string, unknown>> }; return (data.data ?? []).map((item) => finish({ id: `arbeitnow-${String(item.slug)}`, title: String(item.title ?? "Untitled role"), company: String(item.company_name ?? "Unknown company"), location: String(item.location ?? "Not specified"), remote: Boolean(item.remote), source: "Arbeitnow", url: String(item.url ?? ""), publishedAt: item.created_at ? new Date(Number(item.created_at) * 1000).toISOString() : "", description: clean(String(item.description ?? "")), tags: stringArray(item.tags), employmentType: stringArray(item.job_types).join(", ") })); }
async function jobicy(): Promise<Job[]> { const data = await fetchJson("https://jobicy.com/api/v2/remote-jobs?count=200", 10_000) as { jobs?: Array<Record<string, unknown>> }; return (data.jobs ?? []).map((item) => { const salary = item.salaryMin || item.salaryMax ? `${String(item.salaryCurrency ?? "")} ${String(item.salaryMin ?? "")}–${String(item.salaryMax ?? "")} ${String(item.salaryPeriod ?? "")}`.trim() : ""; return { ...finish({ id: `jobicy-${String(item.id)}`, title: String(item.jobTitle ?? "Untitled role"), company: String(item.companyName ?? "Unknown company"), location: String(item.jobGeo ?? "Remote"), remote: true, workplace: "remote", source: "Jobicy", url: String(item.url ?? ""), publishedAt: String(item.pubDate ?? ""), description: clean(String(item.jobDescription ?? item.jobExcerpt ?? "")), tags: stringArray(item.jobIndustry), employmentType: stringArray(item.jobType).join(", ") }), salaryText: salary || undefined, salaryCurrency: String(item.salaryCurrency ?? "") || undefined, liveStatus: "live" as const, liveStatusReason: "Present in Jobicy's current public feed." }; }); }
async function himalayas(): Promise<Job[]> { const data = await fetchJson("https://himalayas.app/jobs/api?limit=20", 10_000) as { jobs?: Array<Record<string, unknown>> }; return (data.jobs ?? []).map((item) => { const restrictions = stringArray(item.locationRestrictions); const location = restrictions.length ? restrictions.join(", ") : "Worldwide remote"; const salary = item.minSalary || item.maxSalary ? `${String(item.currency ?? "")} ${String(item.minSalary ?? "")}–${String(item.maxSalary ?? "")} ${String(item.salaryPeriod ?? "annual")}`.trim() : ""; return { ...finish({ id: `himalayas-${String(item.guid ?? item.applicationLink)}`, title: String(item.title ?? "Untitled role"), company: String(item.companyName ?? "Unknown company"), location, remote: true, workplace: "remote", source: "Himalayas", url: String(item.applicationLink ?? ""), publishedAt: String(item.pubDate ?? ""), description: clean(String(item.description ?? item.excerpt ?? "")), tags: [...stringArray(item.category), ...stringArray(item.parentCategories)], employmentType: String(item.employmentType ?? "") }), salaryText: salary || undefined, salaryCurrency: String(item.currency ?? "") || undefined, closesAt: String(item.expiryDate ?? "") || undefined, liveStatus: item.expiryDate && Date.parse(String(item.expiryDate)) < Date.now() ? "closed" as const : "live" as const, liveStatusReason: item.expiryDate ? "Checked against the source expiry date." : "Present in Himalayas' current public feed." }; }); }
async function remoteOk(): Promise<Job[]> { const data = await fetchJson("https://remoteok.com/api", 10_000) as Array<Record<string, unknown>>; return (Array.isArray(data) ? data : []).filter((item) => item.position || item.url).map((item) => finish({ id: `remoteok-${String(item.id ?? item.slug)}`, title: String(item.position ?? "Untitled role"), company: String(item.company ?? "Unknown company"), location: String(item.location ?? "Worldwide remote"), remote: true, workplace: "remote", source: "Remote OK", url: String(item.url ?? ""), publishedAt: String(item.date ?? ""), description: clean(String(item.description ?? "")), tags: stringArray(item.tags), employmentType: String(item.employment_type ?? "Remote") })); }
function parseBoard(rawUrl: string): BoardTarget | null { try { const url = new URL(rawUrl); const host = url.hostname.toLowerCase(); const parts = url.pathname.split("/").filter(Boolean); let provider: BoardProvider | null = null; let slug: string | undefined; if (["boards.greenhouse.io", "job-boards.greenhouse.io", "boards-api.greenhouse.io"].includes(host)) { provider = "greenhouse"; slug = host === "boards-api.greenhouse.io" ? parts.at(-2) : parts[0]; } else if (["jobs.lever.co", "api.lever.co"].includes(host)) { provider = "lever"; slug = host === "api.lever.co" ? parts[2] : parts[0]; } else if (["jobs.ashbyhq.com", "api.ashbyhq.com"].includes(host)) { provider = "ashby"; slug = host === "api.ashbyhq.com" ? parts.at(-1) : parts[0]; } else if (["jobs.smartrecruiters.com", "api.smartrecruiters.com"].includes(host)) { provider = "smartrecruiters"; slug = host === "api.smartrecruiters.com" ? parts[2] : parts[0]; } return provider && slug && /^[a-z0-9_-]+$/i.test(slug) ? { provider, slug, name: slug } : null; } catch { return null; } }
async function greenhouse(target: BoardTarget): Promise<Job[]> { const data = await fetchJson(`https://boards-api.greenhouse.io/v1/boards/${target.slug}/jobs?content=true`) as { jobs?: Array<Record<string, unknown>> }; return (data.jobs ?? []).map((item) => { const location = typeof item.location === "object" && item.location ? String((item.location as Record<string, unknown>).name ?? "") : ""; return finish({ ...sourceFacts(item), id: `greenhouse-${target.slug}-${String(item.id)}`, title: String(item.title ?? "Untitled role"), company: target.name, location: location || "Not specified", remote: /remote/i.test(location), source: "Greenhouse", url: String(item.absolute_url ?? ""), publishedAt: String(item.first_published ?? ""), description: clean(String(item.content ?? "")), tags: [], employmentType: "" }); }); }
async function lever(target: BoardTarget): Promise<Job[]> { const data = await fetchJson(`https://api.lever.co/v0/postings/${target.slug}?mode=json`) as Array<Record<string, unknown>>; return (Array.isArray(data) ? data : []).map((item) => { const categories = (item.categories ?? {}) as Record<string, unknown>; const location = String(categories.location ?? (Array.isArray(categories.allLocations) ? categories.allLocations.join(", ") : categories.allLocations) ?? "Not specified"); const workplaceText = String(item.workplaceType ?? ""); return finish({ ...sourceFacts(item), id: `lever-${target.slug}-${String(item.id)}`, title: String(item.text ?? "Untitled role"), company: target.name, location, remote: /remote/i.test(`${location} ${workplaceText}`), workplace: inferWorkplace(workplaceText), source: "Lever", url: String(item.hostedUrl ?? item.applyUrl ?? ""), publishedAt: item.createdAt ? new Date(Number(item.createdAt)).toISOString() : "", description: clean(`${String(item.descriptionPlain ?? item.description ?? "")} ${String(item.additionalPlain ?? "")}`), tags: stringArray(categories.team), employmentType: String(categories.commitment ?? "") }); }); }
async function ashby(target: BoardTarget): Promise<Job[]> { const data = await fetchJson(`https://api.ashbyhq.com/posting-api/job-board/${target.slug}?includeCompensation=true`) as { jobs?: Array<Record<string, unknown>> }; return (data.jobs ?? []).map((item) => { const location = String(item.location ?? "Not specified"); const workplaceText = String(item.workplaceType ?? ""); return finish({ ...sourceFacts(item), id: `ashby-${target.slug}-${String(item.id ?? item.jobUrl)}`, title: String(item.title ?? "Untitled role"), company: target.name, location, remote: Boolean(item.isRemote) || /remote/i.test(workplaceText), workplace: inferWorkplace(workplaceText, Boolean(item.isRemote)), source: "Ashby", url: String(item.jobUrl ?? item.applyUrl ?? ""), publishedAt: String(item.publishedAt ?? ""), description: clean(String(item.descriptionPlain ?? item.descriptionHtml ?? "")), tags: [...stringArray(item.department), ...stringArray(item.team)], employmentType: String(item.employmentType ?? "") }); }); }
async function smartRecruiters(target: BoardTarget, scope: GeographyScope, query: string): Promise<Job[]> {
  const params = new URLSearchParams({ limit: "100", destination: "PUBLIC" });
  if (scope === "india") params.set("country", "in");
  if (query) params.set("q", query);
  const items: Array<Record<string, unknown>> = [];
  for (let page = 0; page < 3; page += 1) {
    params.set("offset", String(page * 100));
    const data = await fetchJson(`https://api.smartrecruiters.com/v1/companies/${target.slug}/postings?${params}`) as { content?: Array<Record<string, unknown>>; totalFound?: number };
    items.push(...(data.content ?? []));
    if ((data.content?.length ?? 0) < 100 || items.length >= Number(data.totalFound ?? Infinity)) break;
  }
  return items.map((item) => { const locationData = (item.location ?? {}) as Record<string, unknown>; const countryCode = String(locationData.country ?? "").toUpperCase(); const countryName = /^[A-Z]{2}$/.test(countryCode) ? new Intl.DisplayNames(["en"], { type: "region" }).of(countryCode) : String(locationData.country ?? ""); const parts = [locationData.city, locationData.region, countryName].map(String).filter((value) => value && value !== "undefined"); const location = parts.join(", ") || "Not specified"; const department = (item.department ?? {}) as Record<string, unknown>; const roleFunction = (item.function ?? {}) as Record<string, unknown>; const employment = (item.typeOfEmployment ?? {}) as Record<string, unknown>; const remote = Boolean(locationData.remote); return finish({ ...sourceFacts(item), id: `smartrecruiters-${target.slug}-${String(item.id)}`, title: String(item.name ?? "Untitled role"), company: target.name, location: remote ? `${location} · Remote` : location, remote, workplace: locationData.hybrid ? "hybrid" : remote ? "remote" : "onsite", source: "SmartRecruiters", url: String(item.postingUrl ?? `https://jobs.smartrecruiters.com/${target.slug}/${String(item.id)}`), publishedAt: String(item.releasedDate ?? item.createdOn ?? ""), description: [department.label, roleFunction.label].filter(Boolean).join(" · "), tags: [department.label, roleFunction.label].filter(Boolean).map(String), employmentType: String(employment.label ?? "") }); }); }
function boardJobs(target: BoardTarget, scope: GeographyScope, query: string) { if (target.provider === "greenhouse") return greenhouse(target); if (target.provider === "lever") return lever(target); if (target.provider === "ashby") return ashby(target); return smartRecruiters(target, scope, query); }
function isIndia(job: Job) { return indianPlaces.test(job.location); }
function isWorldwideRemote(job: Job) { return job.workplace === "remote" && worldwidePlaces.test(job.location); }
function locationEligible(job: Job, scope: GeographyScope): boolean { if (scope === "any") return true; if (scope === "india") return isIndia(job) || isWorldwideRemote(job); return !isIndia(job); }
function requestedLocations(requested: string, nearby: boolean): string[] { const wanted = requested.toLowerCase().trim(); if (!wanted) return []; return nearby ? [...new Set([...(cityAliases[wanted] ?? []), ...locationTerms(requested)])] : requested.split(/[,;]/).map((item) => item.trim().toLowerCase()).filter(Boolean); }
function locationScore(job: Job, requested: string, scope: GeographyScope, nearby: boolean): number { const place = job.location.toLowerCase(); const terms = requestedLocations(requested, nearby); if (terms.length && terms.some((term) => place.includes(term))) return 48; if (scope === "india" && isIndia(job)) return 35; if (scope === "international" && !isIndia(job)) return 30; if (isWorldwideRemote(job)) return 20; return 8; }
function locationFit(job: Job, requested: string, scope: GeographyScope, nearby: boolean): Job["locationFit"] { const place = job.location.toLowerCase(); const terms = requestedLocations(requested, nearby); if (terms.length && terms.some((term) => place.includes(term))) return "exact"; if (isWorldwideRemote(job)) return "global-remote"; if (scope === "india" && isIndia(job)) return "india-fallback"; if (scope === "international" && !isIndia(job)) return "international"; return "anywhere"; }
function relevance(job: Job, q: string, categories: RoleCategory[], rolePhrases: string[], mode: "exact" | "balanced" | "broad", optional: string): number { const title = job.title.toLowerCase(); const body = `${job.description} ${job.tags.join(" ")}`.toLowerCase(); const queryTokens = tokens(`${q} ${optional}`); const phrases = categories.flatMap((category) => aliases[category]).concat(rolePhrases, q.toLowerCase()).filter(Boolean); let score = phrases.some((phrase) => title.includes(phrase)) ? 110 : 0; score += queryTokens.filter((term) => title.includes(term)).length * 45; score += queryTokens.filter((term) => body.includes(term)).length * (mode === "broad" ? 10 : 4); if (categories.some((category) => category !== "custom" && aliases[category].some((phrase) => title.includes(phrase) || (mode === "broad" && body.includes(phrase))))) score += 35; return score; }
function categoryMatches(job: Job, categories: RoleCategory[]): boolean { if (!categories.length || categories.includes("custom") || categories.includes("remote") || job.source === "Company Careers") return true; return categories.some((category) => categoryTitlePatterns[category]?.test(job.title)); }
function allowRequest(request: NextRequest): boolean { const key = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "anonymous"; const now = Date.now(); const bucket = rateBuckets.get(key); if (rateBuckets.size > 10_000) for (const [storedKey, stored] of rateBuckets) if (stored.resetAt <= now) rateBuckets.delete(storedKey); if (!bucket || bucket.resetAt <= now) { rateBuckets.set(key, { count: 1, resetAt: now + WINDOW_MS }); return true; } if (bucket.count >= RATE_LIMIT) return false; bucket.count += 1; return true; }

async function executeSearch(input: z.infer<typeof searchSchema>): Promise<SearchResponse> {
  const { q, location, scope, experience, qualification, negative, boards, industry, mode, required, optional, schedule, relocation } = input;
  const categories = (input.categories ? input.categories.split(",") : [input.category]).filter((item): item is RoleCategory => roleCategories.includes(item as RoleCategory));
  const selectedRolePhrases = occupationPhrases(input.roles.split(",").filter(Boolean));
  const workplaces = (input.workplaces ? input.workplaces.split(",") : [input.remote === "true" ? "remote" : input.workplace]).filter((item): item is WorkplaceMode => ["any", "remote", "hybrid", "onsite"].includes(item));
  const userTargets = boards.split("\n").map((url) => parseBoard(url.trim())).filter((target): target is BoardTarget => Boolean(target));
  const registryTargets = categories.flatMap((category) => employersForSearch(category, scope, 24, q));
  const targets = [...new Map([...userTargets, ...registryTargets].map((target) => [`${target.provider}:${target.slug}`, target])).values()].slice(0, 36);
  const tasks: SourceTask[] = [
    { name: "Remotive", source: "Remotive", key: "feed:remotive", load: remotive }, { name: "Arbeitnow", source: "Arbeitnow", key: "feed:arbeitnow", load: arbeitnow },
    { name: "Jobicy", source: "Jobicy", key: "feed:jobicy", ttl: 60 * 60 * 1000, load: jobicy }, { name: "Himalayas", source: "Himalayas", key: "feed:himalayas", load: himalayas }, { name: "Remote OK", source: "Remote OK", key: "feed:remoteok", load: remoteOk },
    ...targets.map((target) => ({ name: `${target.provider}:${target.name}`, source: ({ greenhouse: "Greenhouse", lever: "Lever", ashby: "Ashby", smartrecruiters: "SmartRecruiters" } as const)[target.provider], key: `feed:${target.provider}:${target.slug}${target.provider === "smartrecruiters" ? `:${scope}:${categories.includes("custom") ? q : ""}` : ""}`, load: () => boardJobs(target, scope, categories.includes("custom") ? q : "") }))
  ];
  const checkedAt = new Date().toISOString();
  const outcomes = await mapConcurrent(tasks, 6, async (task) => {
    if (circuitOpen(task.key)) return { status: "disabled" as const, jobs: [] as Job[], cached: false, checkedAt, error: "Temporarily disabled after repeated failures." };
    try { const result = await cached(task.key, task.ttl ?? FEED_TTL_MS, task.load); recordSuccess(task.key); return { status: "healthy" as const, jobs: result.value.map((job) => ({ ...job, lastCheckedAt: result.checkedAt })), cached: result.cached, checkedAt: result.checkedAt }; }
    catch { recordFailure(task.key); return { status: "degraded" as const, jobs: [] as Job[], cached: false, checkedAt, error: "Provider timed out or returned an error." }; }
  });
  const health: SourceHealth[] = outcomes.map((result, index) => ({ name: tasks[index].name, status: result.status, count: result.jobs.length, message: result.error, lastCheckedAt: result.checkedAt, cached: result.cached }));
  const warnings = health.filter((item) => item.status !== "healthy").map((item) => `${item.name} is ${item.status}; other official sources were still searched.`);
  const negatives = negative.split(/[,;\n]/).map((term) => term.trim().toLowerCase()).filter(Boolean); const requiredTerms = required.split(/[,;\n]/).map((term) => term.trim().toLowerCase()).filter(Boolean); const qualificationWords = qualificationTerms[qualification]; const curated = [...new Map(categories.flatMap(curatedJobs).map((job) => [job.id, job])).values()];
  if (curated.length) health.push({ name: "Curated official company careers", status: "healthy", count: curated.length, lastCheckedAt: checkedAt, cached: true });
  const snapshotJobs: Job[] = (snapshot.jobs as Job[]).filter((job) => job.lastCheckedAt && Date.now() - Date.parse(job.lastCheckedAt) < 26 * 60 * 60 * 1000).map((job) => finish(job));
  if (snapshotJobs.length) health.push({ name: "Scheduled official career-page checks", status: "healthy", count: snapshotJobs.length, lastCheckedAt: snapshot.checkedAt ?? undefined, cached: true });
  const gathered = [...outcomes.flatMap((result) => result.jobs), ...snapshotJobs, ...curated];
  const unique = deduplicateJobs(gathered);
  const ranked = unique.map((job) => { const context = `${job.title} ${job.company} ${job.description} ${job.tags.join(" ")}`.toLowerCase(); const roleScore = relevance(job, q, categories, selectedRolePhrases, mode, optional); const roleMatchScore = job.source === "Company Careers" ? Math.max(80, roleScore) : roleScore; const industryBoost = industryTerms[industry].some((term) => context.includes(term)) ? 35 : 0; const fit = locationFit(job, location, scope, input.nearby === "true"); const reasons = [roleScore >= 100 ? "Role title matches" : roleScore >= 45 ? "Relevant title or skills" : "Broader description match", fit === "exact" ? "Requested location or nearby cluster" : fit === "global-remote" ? "Worldwide remote" : fit === "india-fallback" ? "India-based" : fit === "international" ? "International market" : "Location unrestricted", job.freshness === "new" ? "Recently posted" : "", job.employmentType ? `${job.employmentType}` : ""].filter(Boolean); return { ...job, roleMatchScore, relevanceScore: roleMatchScore + industryBoost + locationScore(job, location, scope, input.nearby === "true") + (job.freshness === "new" ? 8 : job.freshness === "recent" ? 4 : 0), matchReasons: reasons, qualification: job.qualification === "Not stated" ? qualificationWords.find((term) => context.includes(term)) ?? "Not stated" : job.qualification, locationFit: fit, lastCheckedAt: job.lastCheckedAt ?? job.verifiedAt }; });
  const context = (job: Job) => `${job.title} ${job.description} ${job.tags.join(" ")}`.toLowerCase();
  const scheduleTerms: Record<string, string[]> = { "full-time": ["full time", "full-time", "permanent"], "part-time": ["part time", "part-time", "parttime"], contract: ["contract", "contractor", "freelance"], internship: ["intern", "internship"], temporary: ["temporary", "temp", "seasonal"], volunteer: ["volunteer"] };
  const threshold = mode === "exact" ? 80 : mode === "broad" ? 25 : 45;
  const { accepted, removedBy } = filterWithDiagnostics<Job>(ranked, [
    ["Closed or invalid listing", (job) => Boolean(job.url) && job.liveStatus !== "closed" && (!job.closesAt || Date.parse(job.closesAt) >= Date.now())],
    ["Recruitment programme", (job) => input.recruitment === "any" || (job.recruitmentTypes ?? []).includes(input.recruitment)],
    ["Country / remote eligibility", (job) => locationEligible(job, scope)],
    ["Role family", (job) => categoryMatches(job, categories)],
    ["Title relevance", (job) => (job.roleMatchScore ?? 0) >= (q || selectedRolePhrases.length || categories.some((category) => category !== "custom") ? threshold : 0)],
    ["City / nearby area", (job) => matchesRequestedLocation(job, requestedLocations(location, input.nearby === "true"))],
    ["Workplace mode", (job) => workplaces.includes("any") || workplaces.includes(job.workplace as WorkplaceMode)],
    ["Excluded keywords", (job) => !negatives.some((term) => job.title.toLowerCase().includes(term))],
    ["Required keywords", (job) => requiredTerms.every((term) => context(job).includes(term))],
    ["Exact title", (job) => mode !== "exact" || !(q || selectedRolePhrases.length) || [q.toLowerCase(), ...selectedRolePhrases].filter(Boolean).some((phrase) => job.title.toLowerCase().includes(phrase))],
    ["Job type", (job) => schedule === "any" || scheduleTerms[schedule].some((term) => `${job.employmentType ?? ""} ${job.title}`.toLowerCase().replaceAll("_", "-").includes(term))],
    ["Relocation", (job) => relocation === "any" || job.relocation === relocation],
    ["Experience / fresher safety", (job) => !((experience === "fresher" || experience === "entry") && (isSeniorRole(job.title) || /\b(?:[3-9]|1[0-9])\+?\s*years?\b/i.test(job.description.slice(0, 700)) || job.experienceLevel === "experienced"))],
    ["Qualification not matched / not stated", (job) => !qualificationWords.length || qualificationWords.some((term) => context(job).includes(term))]
  ]);
  const jobs = accepted.sort((a, b) => (b.relevanceScore ?? 0) - (a.relevanceScore ?? 0) || Date.parse(b.publishedAt || "0") - Date.parse(a.publishedAt || "0")).slice(0, 500);
  const diagnostics = { gathered: gathered.length, duplicatesRemoved: gathered.length - unique.length, returned: jobs.length, removedBy, employersSearched: targets.length, employersAvailable: employerRegistry.length };

  return { jobs, diagnostics, fetchedAt: checkedAt, warnings, sources: [...new Set(tasks.map((task) => task.source).concat(curated.length || snapshotJobs.length ? ["Company Careers"] : []))], health, cache: { status: "miss", maxAgeSeconds: SEARCH_TTL_MS / 1000 } };
}

export async function GET(request: NextRequest) {
  if (!allowRequest(request)) return NextResponse.json({ error: "Too many searches. Wait one minute and try again." }, { status: 429, headers: { "Retry-After": "60" } });
  const parsed = searchSchema.safeParse(Object.fromEntries(request.nextUrl.searchParams)); if (!parsed.success) return NextResponse.json({ error: "Invalid search parameters" }, { status: 400 });
  const cacheKey = `search:${new URLSearchParams(Object.entries(parsed.data).filter(([, value]) => value !== "").sort(([a], [b]) => a.localeCompare(b))).toString()}`;
  const result = await cached(cacheKey, SEARCH_TTL_MS, () => executeSearch(parsed.data));
  return NextResponse.json({ ...result.value, cache: { status: result.cached ? "hit" : "miss", maxAgeSeconds: SEARCH_TTL_MS / 1000 } }, { headers: { "Cache-Control": "public, s-maxage=300, stale-while-revalidate=900", "X-RateLimit-Limit": String(RATE_LIMIT), "X-VEYRA-Cache": result.cached ? "HIT" : "MISS" } });
}
